[application]
name = "perso_ck3-gui"

[desktop]
title = "perso-ck3-gui"

[web.app]
title = "perso-ck3-gui"

# include `assets` in web platform
[web.resource]
#base_path = "gui"

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
