[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.cli]
command = "cargo"
args = ["run", "--package", "cli"]
workspace = false

[tasks.web]
command = "dx"
args = ["serve", "--platform", "web", "--package", "gui"]
workspace = false

[tasks.web-build]
command = "dx"
args = ["bundle", "--platform", "web", "--package", "gui"]
workspace = false

[tasks.desktop]
command = "dx"
args = ["serve", "--platform", "desktop", "--package", "gui"]
workspace = false