[package]
name = "cli"
version = "0.1.0"
authors = ["Waylander <francois.caizes@laposte.net>"]
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
core = { path = "../core" }
