[package]
name = "cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
core = { path = "../core" }
